### ISSUE TITLE
支付2（120元）调起报错，我的手机是小米9，系统是android10

### ISSUE THREAD

**Issue by SteveYung** [xindong/anti-addiction-kit#1]
我使用的是Demo工程
报错信息如下，然后弹出支付限制，我的身份证是超过十八岁的,请问是什么原因呢:
2020-03-02 17:26:04.316 24715-24715/? W/TypefaceUtils: get metaData of com.seraph.gameprotection failed
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
at miui.util.TypefaceUtils.isUsingMiuiFont(TypefaceUtils.java:300)
at miui.util.TypefaceUtils.usingMiuiFonts(TypefaceUtils.java:289)
at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:570)
at android.widget.TextView.replaceTypeface(TextView.java:4380)
at android.widget.TextView.setTypeface(TextView.java:4369)
at android.widget.TextView.setTypeface(TextView.java:2268)
at androidx.appcompat.widget.AppCompatTextView.setTypeface(AppCompatTextView.java:708)
at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2157)
at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2144)
at android.widget.TextView.applyTextAppearance(TextView.java:4083)
at android.widget.TextView.(TextView.java:1604)
at android.widget.TextView.(TextView.java:968)
at androidx.appcompat.widget.AppCompatTextView.(AppCompatTextView.java:99)
at androidx.appcompat.widget.AppCompatTextView.(AppCompatTextView.java:95)
at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1065)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:440)
at android.app.Dialog.setContentView(Dialog.java:573)
at com.antiaddiction.sdk.view.AccountLimitTip.onCreate(AccountLimitTip.java:116)
at android.app.Dialog.dispatchOnCreate(Dialog.java:423)
at android.app.Dialog.show(Dialog.java:317)
at com.antiaddiction.sdk.view.AccountLimitTip$8.run(AccountLimitTip.java:355)
at android.app.Activity.runOnUiThread(Activity.java:6972)
at com.antiaddiction.sdk.view.AccountLimitTip.showAccountLimitTip(AccountLimitTip.java:349)
at com.antiaddiction.sdk.AntiAddictionCore$5.run(AntiAddictionCore.java:328)
at android.app.Activity.runOnUiThread(Activity.java:6972)
at com.antiaddiction.sdk.AntiAddictionCore.checkPayInMainThread(AntiAddictionCore.java:318)
at com.antiaddiction.sdk.AntiAddictionCore.checkPayLimit(AntiAddictionCore.java:245)
at com.antiaddiction.sdk.AntiAddictionKit.checkPayLimit(AntiAddictionKit.java:94)
at com.seraph.gameprotection.MainActivity.onClick(MainActivity.java:168)
at android.view.View.performClick(View.java:7160)
at android.view.View.performClickInternal(View.java:7137)
at android.view.View.access$3500(View.java:810)
at android.view.View$PerformClick.run(View.java:27418)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:7520)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by lc1006** [comment]
请问支付限制弹框里面的提示内容是什么

**Comment by SteveYung** [comment]
健康消费提示
根据国家相关规定，当前无法使用充值相关功能。

**Comment by SteveYung** [comment]
> 请问支付限制弹框里面的提示内容是什么
提示如下
健康消费提示
根据国家相关规定，当前无法使用充值相关功能。

**Comment by lc1006** [comment]
根据提示，应该是输入的身份证信息有误，麻烦确认一下。上面的错误信息只是小米系统内部的提示，不会影响正常功能。可以卸载应用之后，重装试一下
